stages:
  split:
    cmd: python src/data/data_split.py
    deps:
    - data/raw_data/raw.csv
    - src/data/data_split.py
    - src/params.yaml
    outs:
    - data/processed/X_test.csv
    - data/processed/X_train.csv
    - data/processed/y_test.csv
    - data/processed/y_train.csv
  normalize:
    cmd: python src/data/normalize.py
    deps:
    - data/processed/X_test.csv
    - data/processed/X_train.csv
    - src/data/normalize.py
    outs:
    - data/processed/X_test_scaled.csv
    - data/processed/X_train_scaled.csv
