# Parameters

data_split:
  test_size: 0.20
  random_state: 88

grid_search:
  alpha: [0.001, 0.005, 0.01, 0.02, 0.05, 0.08, 0.1, 0.2, 0.6, 1]
  fit_intercept: [True, False]
  solver: ['lbfgs']
  max_iter: [1000]
  cv: 10