# Parameters

data_split:
  test_size: 0.20
  random_state: 123

grid_search:
  alpha: [0.0001, 0.0005, 0.001, 0.002, 0.005, 0.1, 0.2, 0.6, 1]
  fit_intercept: [True, False]
  solver: ['lbfgs']
  max_iter: [500]
  cv: 8