# Parameters

data_split:
  test_size: 0.20
  random_state: 28

grid_search:
  alpha: [0.01, 0.02, 0.05, 0.08, 0.1, 0.2, 0.6, 1, 2, 5]
  fit_intercept: [True, False]
  solver: ['lbfgs']
  max_iter: [100]
  cv: 10